version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container_daiquiriclub
    environment:
      MYSQL_ROOT_PASSWORD: hermitdev
      MYSQL_DATABASE: daiquiriclub
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - daiquiriclub_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_container_daiquiriclub
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://mysql_container_daiquiriclub:3306/daiquiriclub
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=hermitdev
    volumes:
      - ./src:/app/src  # Montar el código fuente para desarrollo
      - ./target:/app/target  # Si usas compilación
    depends_on:
      - mysql
    networks:
      - daiquiriclub_network

networks:
  daiquiriclub_network:

volumes:
  mysql_data:
